# Generated by Django 5.1.6 on 2025-05-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('ACADEMIC', 'Academic'), ('NATURAL_DISASTER', 'Natural Disaster'), ('EMERGENCY', 'Emergency'), ('MEDICAL', 'Medical')], max_length=20),
        ),
    ]
